version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123pormi$
      - POSTGRES_DB=books
    ports:
      - '5432:5432'
    volumes:
      - books-postgres-data:/var/lib/postgresql/data
volumes:
  books-postgres-data:
